### ISSUE TITLE
`/uses` page links are break

### ISSUE THREAD

**Issue by ysm-dev** [tmaximini/maxi.io#2]
https://github.com/tmaximini/maxi.io/blob/master/src/components/Uses/Uses.js

You should probably use `<a>` tag instead of gatsby's `<Link>` for external links.

![image](https://user-images.githubusercontent.com/18487241/72777312-8edf2a00-3c58-11ea-8f4f-d8a9e9c8877f.png)

**Comment by tmaximini** [comment]
thanks man, I somehow missed this totally, I found out the other day. need to work on my notification settings ;)
